from nomad.config.models.plugins import AppEntryPoint
from nomad.config.models.ui import (
    App,
    Column,
    Menu,
    MenuItemCustomQuantities,
    MenuItemDefinitions,
    MenuItemHistogram,
    MenuItemTerms,
)

from nomad_auto_upload_tables.schema_generation import ELN_TAG

app_config = App(
    label='Tabular Data',
    path='tabular-data',
    category='Uploaded Data',
    description=(
        'Structured entries generated after confirming an auto-guessed table '
        'schema (see the nomad-auto-upload-tables plugin).'
    ),
    readme=(
        'Every entry here was created by confirming a schema guess for an '
        'uploaded spreadsheet/CSV file: one entry per table in column mode, '
        'or one entry per source row in row mode. Use "Generated schema" to '
        'filter by the schema a given upload produced, or "Column values" to '
        'search by any of its guessed quantities.'
    ),
    filters_locked={'results.eln.tags': ELN_TAG},
    columns=[
        Column(search_quantity='entry_name', selected=True),
        Column(search_quantity='entry_type', selected=True, title='Generated schema'),
        Column(search_quantity='upload_name', selected=True),
        Column(search_quantity='authors.name', selected=True),
        Column(search_quantity='upload_create_time'),
        Column(search_quantity='mainfile'),
    ],
    menu=Menu(
        items=[
            Menu(title='Generated schema', items=[MenuItemDefinitions()]),
            Menu(
                title='Upload',
                items=[
                    MenuItemTerms(search_quantity='upload_name'),
                    MenuItemTerms(search_quantity='authors.name'),
                    MenuItemHistogram(x='upload_create_time'),
                ],
            ),
            Menu(title='Column values', items=[MenuItemCustomQuantities()]),
        ]
    ),
)

tabular_guess_app = AppEntryPoint(
    name='TabularGuessApp',
    description=(
        'Adds a "Tabular Data" Explore tab listing entries generated by '
        'nomad-auto-upload-tables, searchable by generated schema, upload, '
        'or any guessed column value.'
    ),
    app=app_config,
)
