from nomad.config.models.plugins import AppEntryPoint
from nomad.config.models.ui import (
    App,
    Column,
    Dashboard,
    Layout,
    Menu,
    MenuItemCustomQuantities,
    MenuItemDefinitions,
    MenuItemHistogram,
    MenuItemTerms,
    WidgetScatterPlot,
)

from nomad_auto_upload_tables.schema_generation import ELN_TAG

# TableValues/TableValue (schema_packages/table_values.py) are a fixed plugin
# schema, unlike the per-upload generated schema - their quantities are
# stable across every upload, so a dashboard widget can bind to them with a
# JMESPath filter on `property_name`. See that module's docstring for why the
# per-upload generated schema's own quantities (pressure, temperature, ...)
# can never be used this way, and why TableValue's own quantities must be
# scalars (shape == []) for this to work at all.
#
# NOMAD only exposes schema-package quantities as
# `data.<dotted path>#<fully qualified class name>` (see
# nomad.metainfo.elasticsearch_extension.reload_quantities_dynamic) - plain
# `values.property_name` (no `data.` prefix, no `#<class>` suffix) is never a
# valid search_quantity, dynamic or not.
_TABLE_VALUES_CLASS = 'nomad_auto_upload_tables.schema_packages.table_values.TableValues'


def _table_values_quantity(path: str) -> str:
    return f'data.{path}#{_TABLE_VALUES_CLASS}'


app_config = App(
    label='Tabular Data',
    path='tabular-data',
    category='Uploaded Data',
    description=(
        'Structured entries generated after confirming an auto-guessed table '
        'schema (see the nomad-auto-upload-tables plugin).'
    ),
    readme=(
        'Every entry here was created by confirming a schema guess for an '
        'uploaded spreadsheet/CSV file: one entry per table in column mode, '
        'or one entry per source row in row mode. Use "Generated schema" to '
        'filter by the schema a given upload produced, or "Column values" to '
        'search by any of its guessed quantities.\n\n'
        'The "Temperature vs pressure (example)" dashboard widget plots '
        '`TableValue` entries across *every* upload that has columns guessed '
        'as those names - edit it (or add a new scatter/histogram widget) to '
        'plot any other pair by property name, e.g.:\n\n'
        '```\n'
        f"x: data.values[?property_name=='<name>'].numeric_value#{_TABLE_VALUES_CLASS}\n"
        f"y: data.values[?property_name=='<other_name>'].numeric_value#{_TABLE_VALUES_CLASS}\n"
        '```\n\n'
        'Check "Property names" in the menu for which names are actually '
        'available to plot.'
    ),
    filters_locked={'results.eln.tags': ELN_TAG},
    columns=[
        Column(search_quantity='entry_name', selected=True),
        Column(search_quantity='entry_type', selected=True, title='Generated schema'),
        Column(search_quantity='upload_name', selected=True),
        Column(search_quantity='authors.name', selected=True),
        Column(search_quantity='upload_create_time'),
        Column(search_quantity='mainfile'),
    ],
    menu=Menu(
        items=[
            Menu(title='Generated schema', items=[MenuItemDefinitions()]),
            Menu(
                title='Upload',
                items=[
                    MenuItemTerms(search_quantity='upload_name'),
                    MenuItemTerms(search_quantity='authors.name'),
                    MenuItemHistogram(x='upload_create_time'),
                ],
            ),
            Menu(title='Column values', items=[MenuItemCustomQuantities()]),
            Menu(
                title='Property names',
                items=[MenuItemTerms(search_quantity=_table_values_quantity('values.property_name'), options=20)],
            ),
        ]
    ),
    dashboard=Dashboard(
        widgets=[
            WidgetScatterPlot(
                title='Temperature vs pressure (example)',
                layout={
                    'md': Layout(h=8, w=12, x=0, y=0),
                    'lg': Layout(h=8, w=12, x=0, y=0),
                    'xl': Layout(h=8, w=12, x=0, y=0),
                },
                x={
                    'search_quantity': _table_values_quantity("values[?property_name=='temperature'].numeric_value"),
                    'title': 'Temperature',
                },
                y={
                    'search_quantity': _table_values_quantity("values[?property_name=='pressure'].numeric_value"),
                    'title': 'Pressure',
                },
            ),
        ]
    ),
)

tabular_guess_app = AppEntryPoint(
    name='TabularGuessApp',
    description=(
        'Adds a "Tabular Data" Explore tab listing entries generated by '
        'nomad-auto-upload-tables, searchable by generated schema, upload, '
        'or any guessed column value.'
    ),
    app=app_config,
)
